sudo: true
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq build-essential gettext python-dev zlib1g-dev libpq-dev xvfb
  - sudo apt-get install -qq libtiff4-dev libjpeg8-dev libfreetype6-dev liblcms1-dev libwebp-dev
  - sudo apt-get install -qq graphviz-dev python-setuptools python3-dev python-virtualenv python-pip
  - sudo apt-get install -qq firefox automake libtool libreadline6 libreadline6-dev libreadline-dev
  - sudo apt-get install -qq libsqlite3-dev libxml2 libxml2-dev libssl-dev libbz2-dev wget curl llvm
language: python
services: sqlite
cache:
    directories:
      - $HOME/.cache/pip
before_cache:
    - rm -f $HOME/.cache/pip/log/debug.log
matrix:
    include:
      - python: 3.6
        env: TOX_ENV=py36-django22
      - python: 3.6
        env: TOX_ENV=py36-django30
      - python: 3.6
        env: TOX_ENV=py36-django31
      - python: 3.6
        env: TOX_ENV=py36-django32
      - python: 3.7
        env: TOX_ENV=py37-django22
      - python: 3.7
        env: TOX_ENV=py37-django30
      - python: 3.7
        env: TOX_ENV=py37-django31
      - python: 3.7
        env: TOX_ENV=py37-django32
      - python: 3.8
        env: TOX_ENV=py38-django22
      - python: 3.8
        env: TOX_ENV=py38-django30
      - python: 3.8
        env: TOX_ENV=py38-django31
      - python: 3.8
        env: TOX_ENV=py38-django32
      - python: 3.8
        env: TOX_ENV=py38-django40
      - python: 3.9
        env: TOX_ENV=py39-django22
      - python: 3.9
        env: TOX_ENV=py39-django30
      - python: 3.9
        env: TOX_ENV=py39-django31
      - python: 3.9
        env: TOX_ENV=py39-django32
      - python: 3.9
        env: TOX_ENV=py39-django40
      - python: 3.10
        env: TOX_ENV=py310-django22
      - python: 3.10
        env: TOX_ENV=py310-django30
      - python: 3.10
        env: TOX_ENV=py310-django31
      - python: 3.10
        env: TOX_ENV=py310-django32
      - python: 3.10
        env: TOX_ENV=py310-django40

script: tox -e $TOX_ENV

install:
    - pip install pip setuptools wheel -U
    - pip install -r dev-requirements.txt
    - pip install tox
